name: Check

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: haskell:9.8.2

    steps:
    - uses: actions/checkout@v3

    - name: Update package list
      run: cabal update

    - name: Build
      run: cabal build

    - name: Run tests
      run: cabal test
